export default {
  LogoWhite: require('../assets/images/logo-white.png'),
  Previewbutton: require('../assets/images/Previewbutton.png'),
  Logo: require('../assets/images/Logo.png'),
  Space: require('../assets/images/Space.jpg'),
  Publishbuttoin: require('../assets/images/Publishbuttoin.png'),
  CaptureDecran20220629A125804: require('../assets/images/CaptureDécran20220629À125804.png'),
  _456720Pic: require('../assets/images/456720Pic.png'),
  TestProfThumbnail: require('../assets/images/TestProfThumbnail.png'),
  BgTransparent: require('../assets/images/BgTransparent.png'),
  Sky: require('../assets/images/Sky.jpg'),
  LogoOnlyWhite1: require('../assets/images/LogoOnlyWhite1.png'),
  SansTitre1: require('../assets/images/SansTitre1.png'),
  SansTitre10801920Px: require('../assets/images/SansTitre1080×1920Px.png'),
  SansTitre10801920Px1: require('../assets/images/SansTitre1080×1920Px1.png'),
  SansTitre10801920Px456720Px: require('../assets/images/SansTitre1080×1920Px456×720Px.png'),
  SansTitre2: require('../assets/images/SansTitre2.png'),
  BgHomeUnionApp: require('../assets/images/BgHomeUnionApp.png'),
  BgHomeUnionApp1: require('../assets/images/BgHomeUnionApp1.png'),
  ProfilVectorielAvatarParDefautUtilisateur179376714: require('../assets/images/ProfilVectorielAvatarParDéfautUtilisateur179376714.jpeg'),
};
